wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.12/apache-maven-3.9.12-bin.zip

# ===============================
# CONFIGURACIÓN BASE DE DATOS
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/ikernell_db
spring.datasource.username=fabrica
spring.datasource.password=fabrica2024*

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# PUERTO DEL SERVIDOR
# ===============================

server.port=8080
