spring.application.name=Ikernell-System
spring.datasource.url=jdbc:postgresql://localhost:5432/ikernell_db
spring.datasource.username=fabrica
spring.datasource.password=fabrica2024*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8080
